### ISSUE TITLE
Dropbox location for Models are not publically available.

### ISSUE THREAD

**Issue by akksa** [goru001/inltk#52]
I am trying to download the model for tamil Language. 
https://github.com/goru001/inltk/blob/3e6bf64ec4d4b2ac8231b52b5548cdf4fb97f70a/inltk/config.py#L36.
the dropbox location is not publically available.

**Comment by akksa** [comment]
https://www.dropboxforum.com/t5/Dropbox-installs-integrations/My-public-links-are-no-longer-working/td-p/211934

**Comment by goru001** [comment]
@akksa Thanks for reporting this. I just checked my account and saw that Dropbox blocked my account because excessive traffic was getting generated on it because of model downloads. I've now upgraded it. You should be able to access it now. 

Closing this issue for now. Let me know if you still face any issues.
