### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by soumendrak** [goru001/inltk#6]
Please add support for Windows platform.

**Comment by goru001** [comment]
**FYI for those who want to contribute:** 

I haven't tried out iNLTK/Pytorch on windows, and because of time constraints I don't see that happening in the next 3-4 months. NER and Textual entailment are the two things I'm currently working on.

Having said that, If you're interested in helping, you should setup Pytorch + Fastai on Windows and take it from there! I don't think you need to fiddle around with GPU/CUDA support for pytorch on Windows, as iNLTK doesn't use CUDA. I suspect there might be few issues with fastai on windows, but we should be able to overcome those.

And of course, Shout out if there's anything, I'll be happy to help!

**Comment by goru001** [comment]
Thanks to @ibrahiminfinite, we can now close this issue. @ibrahiminfinite tested iNLTK on Windows 10 and things seem to be running fine (related [PR](https://github.com/goru001/inltk/pull/15)). Installation instructions have been added to README. 

Feel free to report any issues. Thanks!
