### ISSUE TITLE
Suppress warnings in console :SourceChangeWarnings

### ISSUE THREAD

**Issue by jayaBalaR** [goru001/inltk#69]
Environment :- Google Colaboratory
Runtime :- CPU
Installed inltk as directed in the documentation for iNLTK
```
!pip3 install torch==1.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

!pip3 install inltk
```

We are using the function get_similar_sentences() for our case study. We are running this function for our dataset .Dataset size = 9k split in chunks of 1000 records. 
![image](https://user-images.githubusercontent.com/21074002/110633184-77e9f700-81ce-11eb-86a4-647ed13b75af.png)
The code logs warning to the console for each records slowing down the similar sentence generation and taking more than 4 hours for just 1k records.
![image](https://user-images.githubusercontent.com/21074002/110633387-b7b0de80-81ce-11eb-9485-bb021259ae80.png)

We have tried disabling warning using python constructs , but it does not work
Also tried to install latest version of torch and run the code , still facing same issue.
Could you please help disable these warnings or provide a fix for the same.
Thank you
Jayabalambika.R

**Comment by goru001** [comment]
Thanks @jayaBalaR for reaching out. It won't be right to suppress warnings in the library itself. If you want you can hide all warnings by running this at the start of your notebook (from [here](https://stackoverflow.com/questions/9031783/hide-all-warnings-in-ipython)):

`
import warnings

warnings.filterwarnings('ignore')
` 

Additionally, iNLTK depends on torch v1.3 so updating won't help.

About your original concern of speed, the function currently does take time to run on CPU, and since each one of your sentences is being run sequentially, this much time is expected I guess and these warnings don't have anything to do with it. If you really want to speed this up, you can run this on GPU by modifying the iNLTK code (the library doesn't yet support GPU integration unfortunately, and if you feel like, feel free to raise a PR as well for the GPU support.)

**Comment by jayaBalaR** [comment]
@goru001 , Thank you very much for your prompt response.
Actually , we have tried to suppress the warnings by using the code earlier before raising this ticket ,as it did not suppress them.

Now,
1) we have actually segmented my total data_set = 9k into 10 parts . I am running only 1 part of data 1k records, its taking 4 hours + on CPU as per earlier conversation.  Also after trying with CPU on colab we switched the runtime to GPU and still it does take the same 4+hours and now I am able to relate that , though we switch to GPU, internally it runs its CPU implementation only, hence the time.

2)Could you please let us know what would be the approximate time to provide the GPU support, in order for us to estimate and plan the parts in our case study. 
3) Also please let us know whether a separate PRF needs to be raised for GPU support , or you would link the same for GPU support.

Once again thank you very much.

**Comment by goru001** [comment]
@jayaBalaR I can't really give an ETA on GPU support as my hands are full at least for next 2-3 months to be able to work on that.
I think you should be fine if you run `10 separate notebooks` each one with 1k datapoints, and you should be able to get augmentations for 10k datapoints in ~4 hours, given enough CPU power.

Additionally, there's already [this issue](https://github.com/goru001/inltk/issues/5) for GPU support so it should suffice.

**Comment by jayaBalaR** [comment]
@goru001 , thank you, noted  . We will get back in case of any queries on the same issue.

**Comment by goru001** [comment]
Closing this for now since there's already [this issue](https://github.com/goru001/inltk/issues/5) for GPU support, feel free to reopen if there's anything else.
