### ISSUE TITLE
Why the Get Embedding Vectors method gives us 400 dimensions?

### ISSUE THREAD

**Issue by RAJAN8553** [goru001/inltk#80]
I search lot of about this question but didn't find any solution that satisfied my question so i want to know about the hole architecture that why this give us a 400 dimensions and what is the reason behind it. Also which weights are important so that solve my further query.
Kindly help me for this.
Thank you.
Rajan Thakkar

**Comment by goru001** [comment]
Hi @RAJAN8553 , Thanks for reaching out. 

Embedding layer is the first layer of the network which essentially is a map between token ids (of your input sentence) to a vector, which is supposed to be semantic representation of the word in N-dimensional space. Size of this vector (N) is a hyperparameter while training the model, which is 400 in this case. That's why you get 400 dimensional embedding vectors. Let me know if this answers your question.

**Comment by RAJAN8553** [comment]
Yes now i understood Thank you @goru001.

**Comment by RAJAN8553** [comment]
Yes now i understood Thank you @goru001.
Can I tweak that hyperparameter as i need less dimensional or I have to apply feature extraction method.
Can you suggest good feature extraction method for your model.

**Comment by goru001** [comment]
Closing this issue as it is being tracked [here](https://github.com/goru001/inltk/issues/81). Feel free to reopen if there's anything else.
